const Map<String, Map<String, String>> localizedValues = {
  'hu': {
    'femaleGender': 'Nő',
    'maleGender': 'Férfi',
    'otherGender': 'Egyéb',
    'sportsInterest': 'Sport',
    'musicInterest': 'Zene',
    'readingInterest': 'Olvasás',
    'writingInterest': 'Írás',
    'artsInterest': 'Művészetek',
    'dancingInterest': 'Tánc',
    'gardeningInterest': 'Kertészkedés',
    'bakingInterest': 'Konyha',
    'moviesInterest': 'Filmek',
    'travellingInterest': 'Utazás',
    'noEmail': 'Nincs email megadva',
    'wrongEmail': 'A megadott email cím hibás.',
    'noPassword': 'Nincs jelszó megadva',
    'notMatchingPasswords': 'A két jelszó nem egyezik.',
    'wrongPassword':
        "A Jelszónak minimum 8 karakter hosszúnak kell lennie és tartalmaznia kell számokat és betűket",
    'weakPassword': 'A megadott jelszó gyenge',
    'emailAlreadyInUse': 'Az email már használatban van',
    'invalidEmail': 'Az email helytelen',
    'wrongPasswordError': 'A jelszó helytelen',
    'userNotFound': 'A felhsználó nem létezik',
    'userDisabled': 'A felhasználó le van tiltva',
    'tooManyRequests': 'Túl sokszor próbált belépni ezzel a felhasználóval.',
    'sendTheFirstMessage': 'Küldd el az első üzenetet!',
    'sendAMessage': "Üzenj valamit!",
    'noChatPartner': "Nincs chat partner",
    'chat': 'Chat',
    'search': 'Keresés',
    'gallery': "Galéria",
    'description': "Leírás",
    'interests': "Érdeklődési kör",
    'attractedTo': "Vonzódik utána",
    'discover': 'Felfedezés',
    'noMoreCards': "Nincs több kártya 🙁",
    'profile': "Profil",
    'makeNewPhoto': '📷  Új kép készítése',
    'pickFromGallery': '🖼️  Meglévő kép kiválasztása',
    'changeAppColor': "Alkalmazás színének változtatása",
    'chooseColor': 'Válassz színt!',
    'cancel': 'Mégsem',
    'save': "Mentés",
    'edit': 'Szerkesztés',
    'logOut': 'Kijelentkezés',
    'aboutMe': "Leírás rólam",
    'name': "Név",
    'whereAreYou': "Hol vagy a képen?",
    'selectedMyself': 'Kijelöltem magam!',
    'forgotPassword': 'Elfelejtetted a jelszót?',
    'emailAddress': "Email cím",
    'resetPassword': "Jelszó visszaállítása",
    'failedToRequestNewPassword': "Új jelszó kérése sikertelen",
    'passwordResetEmailSent': "Jelszó visszaállító email elküldve.",
    'or': 'Vagy',
    'signInFailed': "A bejelentkezés sikertelen",
    'signInWithGoogle': 'Belépés Google-el',
    'password': "Jelszó",
    'passwordAgain': "Jelszó Újra",
    'registerFailed': 'A regisztráció sikertelen',
    'register': "Regisztráció",
    'signIn': "Bejelentkezés",
    'existing': 'Meglévő',
    'newAccount': 'Új',
    'attractedToQuestion': "Milyen nem(ek) után vonzódsz?",
    'birthDateQuestion': "Mikor születtél?",
    'colorQuestion': "Válassz egy színt, ami tetszik!",
    'descriptionQuestion': "Mesélj magadról!",
    'descriptionHint': "Milyen vagy?",
    'genderQuestion': "Milyen nemű vagy?",
    'interestsQuestion': 'Mi az érdeklődési köröd?',
    'nameQuestion': "Add meg a neved!",
    'nameHint': "A nevem...",
    'imageQuestion': "Hogy nézel ki?",
    'imageHint': "Válassz ki egy képet, amin rajta vagy!",
    'newImage': "Válassz egy képet!",
    'existingImage': "Készíts egy képet!",
    'summaryText': "Helyes így a bemutatkozásod?",
    'summaryHint': "Ezeken később változtathatsz",
    'summeryFinish': "Kész a bemutatkozás!",
    'invalidForm': "A regisztrációhoz tölts ki helyesen minden mezőt!",
    'noFace': "A megadott képen nem található arc!",
    'mName': ' a nevem.',
    //"${widget.state.name} a nevem. 👋\n\n"
    'mDate': 'a születési dátumom.',
    'dateFormat': "yyyy. MM. dd.",
    //"${dateFormat.format(widget.state.birthDate)} a születési dátumom.👶\n\n"
    'mAttractedTo': "Vonzódok utána: ",
    'mInterests': "Érdekel: ",
    'mDescription': 'Néhány szó magamról: ',
    //'Néhány szó magamról: ${widget.state.description}'
  }
};
