const Map<String, Map<String, String>> localizedValues = {
  'hu': {
    'femaleGender': 'Nő',
    'maleGender': 'Férfi',
    'otherGender': 'Egyéb',
    'sportsInterest': 'Sport',
    'musicInterest': 'Zene',
    'readingInterest': 'Olvasás',
    'writingInterest': 'Írás',
    'artsInterest': 'Művészetek',
    'dancingInterest': 'Tánc',
    'gardeningInterest': 'Kertészkedés',
    'bakingInterest': 'Konyha',
    'moviesInterest': 'Filmek',
    'travellingInterest': 'Utazás',
    'noEmail': 'Nincs email megadva',
    'wrongEmail': 'A megadott email cím hibás.',
    'noPassword': 'Nincs jelszó megadva',
    'notMatchingPasswords': 'A két jelszó nem egyezik.',
    'wrongPassword':
        "A Jelszónak minimum 8 karakter hosszúnak kell lennie és tartalmaznia kell legalább egy számot, egy kisbetűt és egy nagybetűt",
    'weakPassword': 'A megadott jelszó gyenge',
    'emailAlreadyInUse': 'Az email már használatban van',
    'invalidEmail': 'Az email helytelen',
    'wrongPasswordError': 'A jelszó helytelen',
    'userNotFound': 'A felhsználó nem létezik',
    'userDisabled': 'A felhasználó le van tiltva',
    'tooManyRequests': 'Túl sokszor próbált belépni ezzel a felhasználóval.',
    'sendTheFirstMessage': 'Küldd el az első üzenetet!',
    'sendAMessage': "Üzenj valamit!",
    'noChatPartner': "Nincs chat partner",
    'chat': 'Chat',
    'search': 'Keresés',
    'gallery': "Galéria",
    'description': "Leírás",
    'interests': "Érdeklődési kör",
    'attractedTo': "Vonzódik utána",
    'discover': 'Felfedezés',
    'noMoreCards': "Nincs több kártya 🙁",
    'profile': "Profil",
    'makeNewPhoto': '📷  Új kép készítése',
    'pickFromGallery': '🖼️  Meglévő kép kiválasztása',
    'changeAppColor': "Alkalmazás színének változtatása",
    'chooseColor': 'Válassz színt!',
    'cancel': 'Mégsem',
    'save': "Mentés",
    'edit': 'Szerkesztés',
    'logOut': 'Kijelentkezés',
    'aboutMe': "Leírás rólam",
    'name': "Név",
    'whereAreYou': "Hol vagy a képen?",
    'selectedMyself': 'Kijelöltem magam!',
    'forgotPassword': 'Elfelejtetted a jelszót?',
    'emailAddress': "Email cím",
    'resetPassword': "Jelszó visszaállítása",
    'failedToRequestNewPassword': "Új jelszó kérése sikertelen",
    'passwordResetEmailSent': "Jelszó visszaállító email elküldve.",
    'or': 'Vagy',
    'signInFailed': "A bejelentkezés sikertelen",
    'signInWithGoogle': 'Belépés Google-el',
    'password': "Jelszó",
    'passwordAgain': "Jelszó Újra",
    'registerFailed': 'A regisztráció sikertelen',
    'register': "Regisztráció",
    'signIn': "Bejelentkezés",
    'existing': 'Meglévő',
    'newAccount': 'Új',
    'attractedToQuestion': "Milyen nem(ek) után vonzódsz?",
    'birthDateQuestion': "Mikor születtél?",
    'colorQuestion': "Válassz egy színt, ami tetszik!",
    'descriptionQuestion': "Mesélj magadról!",
    'descriptionHint': "Milyen vagy?",
    'genderQuestion': "Milyen nemű vagy?",
    'interestsQuestion': 'Mi az érdeklődési köröd?',
    'nameQuestion': "Add meg a neved!",
    'nameHint': "A nevem...",
    'imageQuestion': "Hogy nézel ki?",
    'imageHint': "Válassz ki egy képet, amin rajta vagy!",
    'newImage': "Válassz egy képet!",
    'existingImage': "Készíts egy képet!",
    'summaryText': "Helyes így a bemutatkozásod?",
    'summaryHint': "Ezeken később változtathatsz",
    'summeryFinish': "Kész a bemutatkozás!",
    'invalidForm': "A regisztrációhoz tölts ki helyesen minden mezőt!",
    'noFace': "A megadott képen nem található arc!",
    'mName': ' a nevem.',
    'mDate': 'a születési dátumom.',
    'dateFormat': "yyyy. MM. dd.",
    'mAttractedTo': "Vonzódok utána: ",
    'mInterests': "Érdekel: ",
    'mDescription': 'Néhány szó magamról: ',
    'lang': 'Nyelv',
    'matchTitle': 'Egymásra találtatok!',
    'youAnd': "Te és",
    'likeEachOther': 'kedvelitek egymást!',
  },
  'en': {
    'femaleGender': 'Female',
    'maleGender': 'Male',
    'otherGender': 'Other',
    'sportsInterest': 'Sport',
    'musicInterest': 'Music',
    'readingInterest': 'Reading',
    'writingInterest': 'Writing',
    'artsInterest': 'Arts',
    'dancingInterest': 'Dancing',
    'gardeningInterest': 'Gardening',
    'bakingInterest': 'Baking',
    'moviesInterest': 'Movies',
    'travellingInterest': 'Travelling',
    'noEmail': 'No email provided',
    'wrongEmail': 'The email address is wrong',
    'noPassword': 'No password provided',
    'notMatchingPasswords': "Passwords doesn't match",
    'wrongPassword':
        "Your password must be at least 8 characters long and contain at least one number, one uppercase letter and one lower case letter.",
    'weakPassword': 'The given password is too weak',
    'emailAlreadyInUse': 'The given email is already in use',
    'invalidEmail': 'The email is invalid',
    'wrongPasswordError': 'The password is incorrect',
    'userNotFound': 'The user does not exist',
    'userDisabled': 'The user is disabled',
    'tooManyRequests': 'User has failed in too many login attempts',
    'sendTheFirstMessage': 'Send your first message!',
    'sendAMessage': "Send a message!",
    'noChatPartner': "No chat partner",
    'chat': 'Chat',
    'search': 'Search',
    'gallery': "Gallery",
    'description': "Description",
    'interests': "Intrestes",
    'attractedTo': "Attracted to",
    'discover': 'Discover',
    'noMoreCards': "No more cards 🙁",
    'profile': "Profile",
    'makeNewPhoto': '📷  Take a picture',
    'pickFromGallery': '🖼️  Choose from gallery',
    'changeAppColor': "Change App color",
    'chooseColor': 'Choose a color!',
    'cancel': 'Cancel',
    'save': "Save",
    'edit': 'Edit',
    'logOut': 'Log out',
    'aboutMe': "About me",
    'name': "Name",
    'whereAreYou': "Where are you on the picture?",
    'selectedMyself': 'I selected myself!',
    'forgotPassword': 'Forgot Password?',
    'emailAddress': "Email Address",
    'resetPassword': "Reset password",
    'failedToRequestNewPassword': "Failed to request new password",
    'passwordResetEmailSent': "Password reset email sent.",
    'or': 'or',
    'signInFailed': "Sign in failed",
    'signInWithGoogle': 'Sign in with Google',
    'password': "Password",
    'passwordAgain': "Repeat password",
    'registerFailed': 'Registration failed',
    'register': "Register",
    'signIn': "Sign in",
    'existing': 'Existing',
    'newAccount': 'New Account',
    'attractedToQuestion': "What gender(s) are you attracted to?",
    'birthDateQuestion': "Date of Birth?",
    'colorQuestion': "Choose a color you like!",
    'descriptionQuestion': "Tell about yourself!",
    'descriptionHint': "What do you like?",
    'genderQuestion': "What's your gender?",
    'interestsQuestion': 'What are you interested in?',
    'nameQuestion': "Please enter your name!",
    'nameHint': "My name is...",
    'imageQuestion': "You look like?",
    'imageHint': "Choose a picture of yourself!",
    'newImage': "Select a picture!",
    'existingImage': "Take a picture!",
    'summaryText': "Is your introduction correct?",
    'summaryHint': "You can change theese later",
    'summeryFinish': "You finished your introduction!",
    'invalidForm': "Fill out the fields!",
    'noFace': "No face detected!",
    'mName': ' is my name.',
    'mDate': 'My Date of Birth.',
    'dateFormat': "yyyy. MM. dd.",
    'mAttractedTo': "I'm attracted to: ",
    'mInterests': "I'm intrested in: ",
    'mDescription': 'Few words about me: ',
    'lang': 'Language',
    'matchTitle': "It's a match!",
    'youAnd': "You and",
    'likeEachOther': "like each other!",
  },
  'sr': {
    'femaleGender': 'Žensko',
    'maleGender': 'Muško',
    'otherGender': 'Ostalo',
    'sportsInterest': 'Sport',
    'musicInterest': 'Muzika',
    'readingInterest': 'Čitanje',
    'writingInterest': 'Pisanje',
    'artsInterest': 'Umetnost',
    'dancingInterest': 'Plesanje',
    'gardeningInterest': 'Baštovanstvo',
    'bakingInterest': 'Kuvanje',
    'moviesInterest': 'Filmovi',
    'travellingInterest': 'Putovanje',
    'noEmail': 'Nema email adrese',
    'wrongEmail': 'Pogrešna email adresa',
    'noPassword': 'Nije data lozinka',
    'notMatchingPasswords': 'Lozinke se ne poklapaju',
    'wrongPassword':
        "Vaša lozinka mora da sadrži najmanje 8 karaktera s tim da obavezno mora da sadrži jedno veliko slovo, jedan broj i jedan specijalni znak.",
    'weakPassword': 'Lozinka nije dovoljno bezbedna.',
    'emailAlreadyInUse': 'Email adresa je već u upotrebi',
    'invalidEmail': 'Neispravna email adresa',
    'wrongPasswordError': 'Neispravna lozinka',
    'userNotFound': 'Korisnik ne postoji',
    'userDisabled': 'Korisnik je blokiran',
    'tooManyRequests': 'Previše pokušaja sa istim korisničkim imenom.',
    'sendTheFirstMessage': 'Pošalji svoju prvu poruku',
    'sendAMessage': "Pošalji poruku!",
    'noChatPartner': "Nema partnera za ćaskanje",
    'chat': 'Ćaskanje',
    'search': 'Pretraga',
    'gallery': "Galerija",
    'description': "Opis",
    'interests': "Interesovanja",
    'attractedTo': "Ja privlačim",
    'discover': 'Otkrivanje',
    'noMoreCards': "Nema više karata 🙁",
    'profile': "Profil",
    'makeNewPhoto': '📷  Napravi novu sliku',
    'pickFromGallery': '🖼️  Izaberi postojeću sliku',
    'changeAppColor': "Promeni boju aplikacije",
    'chooseColor': 'Izaberi boju!',
    'cancel': 'Otkaži',
    'save': "Sačuvaj",
    'edit': 'Uredi',
    'logOut': 'Odjavi se',
    'aboutMe': "O meni",
    'name': "Ime",
    'whereAreYou': "Gde si na slici?",
    'selectedMyself': 'Izabrao(la) sam sebe!',
    'forgotPassword': 'Zaboravio(la) sam svoju lozinku',
    'emailAddress': "Email adresa",
    'resetPassword': "Resetuj lozinku",
    'failedToRequestNewPassword': "Zahtev za novu lozinku je neuspešna",
    'passwordResetEmailSent': "Poruka poslata za resetovanje lozinke.",
    'or': 'ili',
    'signInFailed': "Prijava nije uspela",
    'signInWithGoogle': 'Prijavi se preko Google',
    'password': "Lozinka",
    'passwordAgain': "Ponovi lozinku",
    'registerFailed': 'Neuspešna registracija',
    'register': "Registracija",
    'signIn': "Prijavite se",
    'existing': 'Postojeća',
    'newAccount': 'Nova',
    'attractedToQuestion': "Koji pol te privlači",
    'birthDateQuestion': "Datum rođenja?",
    'colorQuestion': "Ova boja mi se sviđa!",
    'descriptionQuestion': "O meni!",
    'descriptionHint': "Kakav(va) si?",
    'genderQuestion': "Koji si pol?",
    'interestsQuestion': 'Moja interesovanja',
    'nameQuestion': "Unesite svoje ime!",
    'nameHint': "Moje ime je...",
    'imageQuestion': "Kako izgledaš?",
    'imageHint': "Izaberi jednu sliku osebi!",
    'newImage': "Izaberi sliku!",
    'existingImage': "Napravi sliku!",
    'summaryText': "Da li je opis tačna?",
    'summaryHint': "Podatke možete promeniti i kasnije",
    'summeryFinish': "Završio si svoj opis!",
    'invalidForm': "Popuni sva polja za registraciju!",
    'noFace': "Ne postoji lice na slici!",
    'mName': ' Moje ime je.',
    'mDate': 'Moj datum rođenja je.',
    'dateFormat': "dd. MM. yyyy.",
    'mAttractedTo': "ja privlačim: ",
    'mInterests': "Interesovanja: ",
    'mDescription': 'Nekoliko reči o sebi: ',
    'lang': 'Jezik',
    'matchTitle': 'Našli ste se jedno drugo!',
    'youAnd': 'Ti i',
    'likeEachOther': 'se dopadate jedno drugom',
  }
};
